version: '3.8'

#networks
networks:
  api:
    driver: bridge
# serviços
services:
    # banco de dados
    api_mysql:
      image: mysql:5.7
      container_name: api_mysql
      command: --innodb-use-native-aio=0
      volumes:
      - ./run/var:/var/lib/mysql
      ports:
      - "3307:3306"
      environment:
        MYSQL_DATABASE: controle_gastos
        MYSQL_ROOT_PASSWORD: laravel
      networks:
        - api
        
    api_nginx:
      # servidor
      image: nginx:alpine
      container_name: api_nginx
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./backend:/application
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8181:80"
      links:
        - api_mysql
      networks:
        - api
    # php
    api_php:
      build: 
        context: .
        dockerfile: backend/Dockerfile
      container_name: api_php
      restart: unless-stopped
      tty: true
      volumes:
        - ./backend:/application
      working_dir: /application
      #command: bash -c script.sh
      networks:
        - api
      depends_on:
      - api_mysql
      